src/JE/FinancesBundle/Entity/PaymentSlip.php
<?php

namespace JE\FinancesBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * PaymentSlip
 *
 * @ORM\Table(name="je_payment_slip")
 * @ORM\Entity(repositoryClass="JE\FinancesBundle\Entity\PaymentSlipRepository")
 * @UniqueEntity("bv")
 * @Gedmo\Uploadable(allowOverwrite = true, filenameGenerator = "SHA1")
 */
class PaymentSlip
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="ref", type="string", length=40)
     * @Assert\NotBlank()
     * @Assert\Regex("/^\d+$/")
     */
    private $ref;

    /**
     * @var string
     *
     * @ORM\Column(name="bv", type="string", length=40, unique=true)
     * @Assert\NotBlank()
     * @Assert\Regex("/^BV\d+$/")
     */
    private $bv;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created_at", type="datetime")
     * @Assert\NotBlank()
     */
    private $createdAt;

    /**
     * @var string
     *
     * @ORM\Column(name="client", type="string", length=255)
     * @Assert\NotBlank()
     */
    private $client;

    /**
     * @var string
     *
     * @ORM\Column(name="student", type="string", length=255)
     * @Assert\NotBlank()
     */
    private $student;

    /**
     * @var integer
     *
     * @ORM\Column(name="amount", type="integer")
     * @Assert\NotBlank()
     */
    private $amount;

    /**
     * @var integer
     *
     * @ORM\Column(name="number_of_days", type="integer")
     * @Assert\NotBlank()
     */
    private $numberOfDays;

    /**
     * @var integer
     *
     * @ORM\Column(name="smic", type="integer")
     * @Assert\NotBlank()
     */
    private $smic;

    /**
     * @var integer
     *
     * @ORM\Column(name="urssaf_1_1", type="integer")
     * @Assert\NotBlank()
     */
    private $urssaf_1_1;

    /**
     * @var integer
     *
     * @ORM\Column(name="urssaf_1_2", type="integer")
     * @Assert\NotBlank()
     */
    private $urssaf_1_2;

    /**
     * @var integer
     *
     * @ORM\Column(name="urssaf_2_1", type="integer")
     * @Assert\NotBlank()
     */
    private $urssaf_2_1;

    /**
     * @var integer
     *
     * @ORM\Column(name="urssaf_2_2", type="integer")
     * @Assert\NotBlank()
     */
    private $urssaf_2_2;

    /**
     * @var integer
     *
     * @ORM\Column(name="urssaf_2_3", type="integer")
     * @Assert\NotBlank()
     */
    private $urssaf_2_3;

    /**
     * @var integer
     *
     * @ORM\Column(name="urssaf_2_4", type="integer")
     * @Assert\NotBlank()
     */
    private $urssaf_2_4;

    /**
     * @var string
     *
     * @ORM\Column(name="path", type="string", length=255, nullable=true)
     * @Gedmo\UploadableFilePath
     */
    private $path;

    /**
     * @Assert\File(
     *     maxSize="8M",
     *     mimeTypes = {
     *      "application/pdf",
     *      "application/zip", "application/x-compressed", "application/x-zip-compressed", "multipart/x-zip",
     *      "application/excel", "application/vnd.ms-excel", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "application/x-excel", "application/x-msexcel",
     *      "application/msword", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"},
     *     mimeTypesMessage = "Fichier ZIP, PDF, Word ou Excel",
     *     maxSizeMessage = "Fichier trop gros (8Mo max)"
     * )
     */
    private $file;

    public function __construct(Variable $smic = null, Variable $urssaf_1_1 = null, Variable $urssaf_1_2 = null, Variable $urssaf_2_1 = null, Variable $urssaf_2_2 = null, Variable $urssaf_2_3 = null, Variable $urssaf_2_4 = null)
    {
        $this->bv = 'BV';
        $this->createdAt = new \DateTime;

        if($smic !== null)
            $this->setSmic($smic->getValue());
        if($urssaf_1_1 !== null)
            $this->setUrssaf11($urssaf_1_1->getValue());
        if($urssaf_1_2 !== null)
            $this->setUrssaf12($urssaf_1_2->getValue());
        if($urssaf_2_1 !== null)
            $this->setUrssaf21($urssaf_2_1->getValue());
        if($urssaf_2_2 !== null)
            $this->setUrssaf22($urssaf_2_2->getValue());
        if($urssaf_2_3 !== null)
            $this->setUrssaf23($urssaf_2_3->getValue());
        if($urssaf_2_4 !== null)
            $this->setUrssaf24($urssaf_2_4->getValue());
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set ref
     *
     * @param string $ref
     * @return PaymentSlip
     */
    public function setRef($ref)
    {
        $this->ref = $ref;
    
        return $this;
    }

    /**
     * Get ref
     *
     * @return string 
     */
    public function getRef()
    {
        return $this->ref;
    }

    /**
     * Set bv
     *
     * @param string $bv
     * @return PaymentSlip
     */
    public function setBv($bv)
    {
        $this->bv = $bv;
    
        return $this;
    }

    /**
     * Get bv
     *
     * @return string 
     */
    public function getBv()
    {
        return $this->bv;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return PaymentSlip
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    
        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set client
     *
     * @param string $client
     * @return PaymentSlip
     */
    public function setClient($client)
    {
        $this->client = $client;
    
        return $this;
    }

    /**
     * Get client
     *
     * @return string 
     */
    public function getClient()
    {
        return $this->client;
    }

    /**
     * Set student
     *
     * @param string $student
     * @return PaymentSlip
     */
    public function setStudent($student)
    {
        $this->student = $student;
    
        return $this;
    }

    /**
     * Get student
     *
     * @return string 
     */
    public function getStudent()
    {
        return $this->student;
    }

    /**
     * Set amount
     *
     * @param integer $amount
     * @return PaymentSlip
     */
    public function setAmount($amount)
    {
        $this->amount = $this->strToNormalized($amount);
    
        return $this;
    }

    /**
     * Get amount
     *
     * @return integer 
     */
    public function getAmount()
    {
        return $this->normalizedToFloat($this->amount);
    }

    public function getUrssaf()
    {
        return $this->numberOfDays * 4 * $this->getSmic() * ($this->getUrssaf21() + $this->getUrssaf22() + $this->getUrssaf23() + $this->getUrssaf24())/100 + $this->getAmount() * ($this->getUrssaf11() + $this->getUrssaf12())/100;
    }

    public function getTotalAmount()
    {
        return $this->getAmount() - $this->getUrssaf();
    }

    /**
     * Set numberOfDays
     *
     * @param integer $numberOfDays
     * @return PaymentSlip
     */
    public function setNumberOfDays($numberOfDays)
    {
        $this->numberOfDays = $numberOfDays;
    
        return $this;
    }

    /**
     * Get numberOfDays
     *
     * @return integer 
     */
    public function getNumberOfDays()
    {
        return $this->numberOfDays;
    }

    /**
     * @param int $smic
     */
    public function setSmic($smic)
    {
        $this->smic = $this->strToNormalized($smic);
    }

    /**
     * @return int
     */
    public function getSmic()
    {
        return $this->normalizedToFloat($this->smic);
    }

    /**
     * @param int $urssaf_1_1
     */
    public function setUrssaf11($urssaf_1_1)
    {
        $this->urssaf_1_1 = $this->strToNormalized($urssaf_1_1);
    }

    /**
     * @return int
     */
    public function getUrssaf11()
    {
        return $this->normalizedToFloat($this->urssaf_1_1);
    }

    /**
     * @param int $urssaf_1_2
     */
    public function setUrssaf12($urssaf_1_2)
    {
        $this->urssaf_1_2 = $this->strToNormalized($urssaf_1_2);
    }

    /**
     * @return int
     */
    public function getUrssaf12()
    {
        return $this->normalizedToFloat($this->urssaf_1_2);
    }

    /**
     * @param int $urssaf_2_1
     */
    public function setUrssaf21($urssaf_2_1)
    {
        $this->urssaf_2_1 = $this->strToNormalized($urssaf_2_1);
    }

    /**
     * @return int
     */
    public function getUrssaf21()
    {
        return $this->normalizedToFloat($this->urssaf_2_1);
    }

    /**
     * @param int $urssaf_2_2
     */
    public function setUrssaf22($urssaf_2_2)
    {
        $this->urssaf_2_2 = $this->strToNormalized($urssaf_2_2);
    }

    /**
     * @return int
     */
    public function getUrssaf22()
    {
        return $this->normalizedToFloat($this->urssaf_2_2);
    }

    /**
     * @param int $urssaf_2_3
     */
    public function setUrssaf23($urssaf_2_3)
    {
        $this->urssaf_2_3 = $this->strToNormalized($urssaf_2_3);
    }

    /**
     * @return int
     */
    public function getUrssaf23()
    {
        return $this->normalizedToFloat($this->urssaf_2_3);
    }

    /**
     * @param int $urssaf_2_4
     */
    public function setUrssaf24($urssaf_2_4)
    {
        $this->urssaf_2_4 = $this->strToNormalized($urssaf_2_4);
    }

    /**
     * @return int
     */
    public function getUrssaf24()
    {
        return $this->normalizedToFloat($this->urssaf_2_4);
    }

    /**
     * Set path
     *
     * @param string $path
     * @return PaymentSlip
     */
    public function setPath($path)
    {
        $this->path = $path;

        return $this;
    }

    /**
     * Get path
     *
     * @return string
     */

src/JE/FinancesBundle/Entity/SupplierInvoice.php
<?php

namespace JE\FinancesBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * SupplierInvoice
 *
 * @ORM\Table(name="je_supplier_invoice")
 * @ORM\Entity(repositoryClass="JE\FinancesBundle\Entity\SupplierInvoiceRepository")
 * @UniqueEntity("ref")
 */
class SupplierInvoice
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="ref", type="string", length=255, unique=true)
     * @Assert\NotBlank()
     * @Assert\Regex("/^[RF]F\d+$/")
     */
    private $ref;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created_at", type="datetime")
     * @Assert\NotBlank()
     */
    private $createdAt;

    /**
     * @var string
     *
     * @ORM\Column(name="supplier", type="string", length=255)
     * @Assert\NotBlank()
     */
    private $supplier;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="string", length=255)
     * @Assert\NotBlank()
     */
    private $description;

    /**
     * @var integer
     *
     * @ORM\Column(name="totalAmount", type="integer")
     * @Assert\NotBlank()
     */
    private $totalAmount;

    /**
     * @var integer
     *
     * @ORM\Column(name="taxes_high", type="integer", nullable=true)
     */
    private $taxesHigh;

    /**
     * @var integer
     *
     * @ORM\Column(name="taxes_medium", type="integer", nullable=true)
     */
    private $taxesMedium;

    /**
     * @var integer
     *
     * @ORM\Column(name="taxes_low", type="integer", nullable=true)
     */
    private $taxesLow;

    public function __construct()
    {
        $this->createdAt = new \DateTime;
    }


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set ref
     *
     * @param string $ref
     * @return SupplierInvoice
     */
    public function setRef($ref)
    {
        $this->ref = $ref;
    
        return $this;
    }

    /**
     * Get ref
     *
     * @return string 
     */
    public function getRef()
    {
        return $this->ref;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return SupplierInvoice
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    
        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set supplier
     *
     * @param string $supplier
     * @return SupplierInvoice
     */
    public function setSupplier($supplier)
    {
        $this->supplier = $supplier;
    
        return $this;
    }

    /**
     * Get supplier
     *
     * @return string 
     */
    public function getSupplier()
    {
        return $this->supplier;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return SupplierInvoice
     */
    public function setDescription($description)
    {
        $this->description = $description;
    
        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set totalAmount
     *
     * @param integer $totalAmount
     * @return SupplierInvoice
     */
    public function setTotalAmount($totalAmount)
    {
        $this->totalAmount = $this->strToNormalized($totalAmount);
    
        return $this;
    }

    /**
     * Get totalAmount
     *
     * @return integer 
     */
    public function getTotalAmount()
    {
        return $this->normalizedToFloat($this->totalAmount);
    }

    public function getAmount()
    {
        return $this->getTotalAmount() - $this->getTaxesHigh() - $this->getTaxesMedium() - $this->getTaxesLow();
    }

    public function getTaxesAmount()
    {
        return $this->getTaxesHigh() + $this->getTaxesMedium() + $this->getTaxesLow();
    }

    /**
     * Set taxesHigh
     *
     * @param integer $taxesHigh
     * @return SupplierInvoice
     */
    public function setTaxesHigh($taxesHigh)
    {
        $this->taxesHigh = $this->strToNormalized($taxesHigh);
    
        return $this;
    }

    /**
     * Get taxesHigh
     *
     * @return integer 
     */
    public function getTaxesHigh()
    {
        return $this->normalizedToFloat($this->taxesHigh);
    }

    /**
     * Set taxesMedium
     *
     * @param integer $taxesMedium
     * @return SupplierInvoice
     */
    public function setTaxesMedium($taxesMedium)
    {
        $this->taxesMedium = $this->strToNormalized($taxesMedium);
    
        return $this;
    }

    /**
     * Get taxesMedium
     *
     * @return integer 
     */
    public function getTaxesMedium()
    {
        return $this->normalizedToFloat($this->taxesMedium);
    }

    /**
     * Set taxesLow
     *
     * @param integer $taxesLow
     * @return SupplierInvoice
     */
    public function setTaxesLow($taxesLow)
    {
        $this->taxesLow = $this->strToNormalized($taxesLow);
    
        return $this;
    }

    /**
     * Get taxesLow
     *
     * @return integer 
     */
    public function getTaxesLow()
    {
        return $this->normalizedToFloat($this->taxesLow);
    }

    private function strToNormalized($str)
    {
        $str = str_replace(',', '.', $str);
        $str = str_replace(' ', '', $str);
        return intval(100 * floatval($str));
    }

    private function normalizedToFloat($int)
    {
        if($int === null) return null;
        return floatval($int / 100);
    }
}

src/JE/FinancesBundle/Controller/TreasuryController.php
<?php

namespace JE\FinancesBundle\Controller;

use JE\FinancesBundle\Services\DateHelper;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use JMS\SecurityExtraBundle\Annotation\Secure;
use Doctrine\ORM\EntityManager;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Form;

class TreasuryController extends Controller
{
    /** @var  EntityManager */
    private $em;

    /** @var  Request */
    private $request;

    /**
     * @Secure(roles="ROLE_TREZ_VIEW")
     * @Template
     */
    public function indexAction($month, $year)
    {
        /** @var DateHelper $dateHelper */
        $dateHelper = $this->get('je.finances.date_helper');

        $yearRange = $dateHelper->getYearRange(array(
            'JEFinancesBundle:CustomerInvoice',
            'JEFinancesBundle:PaymentSlip',
            'JEFinancesBundle:SupplierInvoice',
        ));

        list($month, $year)                     = $dateHelper->getDefaultDate($month, $year, $yearRange);
        list($sales, $salesSum)                 = $dateHelper->dataFromMonth('JEFinancesBundle:CustomerInvoice');
        list($purchases, $purchasesSum)         = $dateHelper->dataFromMonth('JEFinancesBundle:SupplierInvoice');
        list($paymentSlips, $paymentSlipsSum)   = $dateHelper->dataFromMonth('JEFinancesBundle:PaymentSlip');

        return array(
            'month' => $month,
            'year' => $year,
            'dateRange' => $yearRange,
            'sales' => $sales,
            'salesSum' => $salesSum,
            'purchases' => $purchases,
            'purchasesSum' => $purchasesSum,
            'paymentSlips' => $paymentSlips,
            'paymentSlipsSum' => $paymentSlipsSum,
        );
    }
}

src/JE/FinancesBundle/Resources/views/Treasury/index.html.twig
{% extends '::layout.html.twig' %}

{% block content %}
    <h1 class="ui header">
        Trésorerie réelle
    </h1>
    <div>
        Affichage du mois de
        <div class="ui inline dropdown">
            <input name="month" type="hidden" value="{{ month }}">
            <div class="text">Mois</div>
            <i class="dropdown icon"></i>
            <div class="menu">
                {% for key, m in months() %}
                    <a href="{{ path('je_finances_treasury', {month:key, year:year}) }}" class="item" data-value="{{ key }}">{{ m }}</a>
                {% endfor %}
            </div>
        </div>
        <div class="ui inline dropdown">
            <input name="gender" type="hidden" value="{{ year }}">
            <div class="text">Année</div>
            <i class="dropdown icon"></i>
            <div class="menu">
                {% for y in range(dateRange.min, dateRange.max) %}
                    <a href="{{ path('je_finances_treasury', {month:month, year:y}) }}" class="item" data-value="{{ y }}">{{ y }}</a>
                {% endfor %}
            </div>
        </div>
    </div>

    <h2>Résumé</h2>

    <table class="ui compact collapsing table segment">
        <tbody>
            <tr>
                <th>TVA</th>
                <td>{{ (salesSum.taxesAmount - purchasesSum.taxesAmount)|money }}</td>
            </tr>
            <tr>
                <th>Entrées</th>
                <td>{{ salesSum.totalAmount|money }}</td>
            </tr>
            <tr>
                <th>Sorties</th>
                <td>{{ (purchasesSum.totalAmount + paymentSlipsSum.totalAmount)|money }}</td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <th>Résultat</th>
                <td>{{ (salesSum.totalAmount - purchasesSum.totalAmount - paymentSlipsSum.totalAmount)|money }}</td>
            </tr>
        </tfoot>
    </table>

    <h2>Ventes</h2>
    <table class="ui compact table segment">
        <thead>
        <tr>
            <th>Référence</th>
            <th>Date d'émmission</th>
            <th>Date du paiment</th>
            <th>Client</th>
            <th>Pourcentage</th>
            <th>Montant HT</th>
            <th>Montant TVA</th>
            <th>Montant TTC</th>
        </tr>
        </thead>
        <tbody>
        {% for invoice in sales %}
            <tr>
                <td>{{ invoice.fc }}</td>
                <td>{{ invoice.issuedAt|date('d/m/Y') }}</td>
                <td>{{ invoice.paidAt|date('d/m/Y') }}</td>
                <td>{{ invoice.client }}</td>
                <td>{{ invoice.percentage }} %</td>
                <td>{{ invoice.amount|money }}</td>
                <td>{{ invoice.taxesAmount|money }}</td>
                <td>{{ invoice.totalAmount|money }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">
                    Aucun FC pour ce mois
                </td>
            </tr>
        {% endfor %}
        </tbody>
        <tfoot>
        <tr>
            <th colspan="5">
                Totale
            </th>
            <th>{{ salesSum.amount|money }}</th>
            <th>{{ salesSum.taxesAmount|money }}</th>
            <th>{{ salesSum.totalAmount|money }}</th>
        </tr>
        </tfoot>
    </table>

    <h2>Achats</h2>
    <table class="ui compact table segment">
        <thead>
            <tr>
                <th>Référence</th>
                <th>Date</th>
                <th>Récepteur</th>
                <th>Description</th>
                <th>Montant HT</th>
                <th>Montant TVA</th>
                <th>Montant TTC</th>
            </tr>
        </thead>
        <tbody>
            {% for purchase in purchases %}
                <tr>
                    <td>{{ purchase.ref }}</td>
                    <td>{{ purchase.createdAt|date('d/m/Y') }}</td>
                    <td>{{ purchase.supplier }}</td>
                    <td>{{ purchase.description }}</td>
                    <td>{{ purchase.amount|money }}</td>
                    <td>{{ purchase.taxesAmount|money }}</td>
                    <td>{{ purchase.totalAmount|money }}</td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="7">
                        Aucun achat pour ce mois
                    </td>
                </tr>
            {%  endfor %}
        </tbody>
        <tfoot>
            <tr>
                <th colspan="4">
                    Totale
                </th>
                <th>{{ purchasesSum.amount|money }}</th>
                <th>{{ purchasesSum.taxesAmount|money }}</th>
                <th>{{ purchasesSum.totalAmount|money }}</th>
            </tr>
        </tfoot>
    </table>

    <h2>Bulletins de versement </h2>

    <table class="ui compact table segment">
        <thead>
        <tr>
            <th>Référence</th>
            <th>Date</th>
            <th>Client</th>
            <th>Réalisateur</th>
            <th>Montant HT</th>
            <th>URSSAF</th>
            <th>Montant TTC</th>
        </tr>
        </thead>
        <tbody>
        {% for slip in paymentSlips %}
            <tr>
                <td>{{ slip.bv }}</td>
                <td>{{ slip.createdAt|date('d/m/Y') }}</td>
                <td>{{ slip.client }}</td>
                <td>{{ slip.student }}</td>
                <td>{{ slip.amount|money }}</td>
                <td>{{ slip.urssaf|money }}</td>
                <td>{{ slip.totalAmount|money }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">
                    Aucun BV pour ce mois
                </td>
            </tr>
        {% endfor %}
        </tbody>
        <tfoot>
        <tr>
            <th colspan="4">
                Totale
            </th>
            <th>{{ paymentSlipsSum.amount|money }}</th>
            <th>{{ paymentSlipsSum.urssaf|money }}</th>
            <th>{{ paymentSlipsSum.totalAmount|money }}</th>
        </tr>
        </tfoot>
    </table>
{% endblock %}