src/JE/FinancesBundle/Entity/SupplierInvoice.php
<?php

namespace JE\FinancesBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * SupplierInvoice
 *
 * @ORM\Table(name="je_supplier_invoice")
 * @ORM\Entity(repositoryClass="JE\FinancesBundle\Entity\SupplierInvoiceRepository")
 * @UniqueEntity("ref")
 */
class SupplierInvoice
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="ref", type="string", length=255, unique=true)
     * @Assert\NotBlank()
     * @Assert\Regex("/^[RF]F\d+$/")
     */
    private $ref;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created_at", type="datetime")
     * @Assert\NotBlank()
     */
    private $createdAt;

    /**
     * @var string
     *
     * @ORM\Column(name="supplier", type="string", length=255)
     * @Assert\NotBlank()
     */
    private $supplier;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="string", length=255)
     * @Assert\NotBlank()
     */
    private $description;

    /**
     * @var integer
     *
     * @ORM\Column(name="totalAmount", type="integer")
     * @Assert\NotBlank()
     */
    private $totalAmount;

    /**
     * @var integer
     *
     * @ORM\Column(name="taxes_high", type="integer", nullable=true)
     */
    private $taxesHigh;

    /**
     * @var integer
     *
     * @ORM\Column(name="taxes_medium", type="integer", nullable=true)
     */
    private $taxesMedium;

    /**
     * @var integer
     *
     * @ORM\Column(name="taxes_low", type="integer", nullable=true)
     */
    private $taxesLow;

    public function __construct()
    {
        $this->createdAt = new \DateTime;
    }


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set ref
     *
     * @param string $ref
     * @return SupplierInvoice
     */
    public function setRef($ref)
    {
        $this->ref = $ref;
    
        return $this;
    }

    /**
     * Get ref
     *
     * @return string 
     */
    public function getRef()
    {
        return $this->ref;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return SupplierInvoice
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    
        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set supplier
     *
     * @param string $supplier
     * @return SupplierInvoice
     */
    public function setSupplier($supplier)
    {
        $this->supplier = $supplier;
    
        return $this;
    }

    /**
     * Get supplier
     *
     * @return string 
     */
    public function getSupplier()
    {
        return $this->supplier;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return SupplierInvoice
     */
    public function setDescription($description)
    {
        $this->description = $description;
    
        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set totalAmount
     *
     * @param integer $totalAmount
     * @return SupplierInvoice
     */
    public function setTotalAmount($totalAmount)
    {
        $this->totalAmount = $this->strToNormalized($totalAmount);
    
        return $this;
    }

    /**
     * Get totalAmount
     *
     * @return integer 
     */
    public function getTotalAmount()
    {
        return $this->normalizedToFloat($this->totalAmount);
    }

    public function getAmount()
    {
        return $this->getTotalAmount() - $this->getTaxesHigh() - $this->getTaxesMedium() - $this->getTaxesLow();
    }

    public function getTaxesAmount()
    {
        return $this->getTaxesHigh() + $this->getTaxesMedium() + $this->getTaxesLow();
    }

    /**
     * Set taxesHigh
     *
     * @param integer $taxesHigh
     * @return SupplierInvoice
     */
    public function setTaxesHigh($taxesHigh)
    {
        $this->taxesHigh = $this->strToNormalized($taxesHigh);
    
        return $this;
    }

    /**
     * Get taxesHigh
     *
     * @return integer 
     */
    public function getTaxesHigh()
    {
        return $this->normalizedToFloat($this->taxesHigh);
    }

    /**
     * Set taxesMedium
     *
     * @param integer $taxesMedium
     * @return SupplierInvoice
     */
    public function setTaxesMedium($taxesMedium)
    {
        $this->taxesMedium = $this->strToNormalized($taxesMedium);
    
        return $this;
    }

    /**
     * Get taxesMedium
     *
     * @return integer 
     */
    public function getTaxesMedium()
    {
        return $this->normalizedToFloat($this->taxesMedium);
    }

    /**
     * Set taxesLow
     *
     * @param integer $taxesLow
     * @return SupplierInvoice
     */
    public function setTaxesLow($taxesLow)
    {
        $this->taxesLow = $this->strToNormalized($taxesLow);
    
        return $this;
    }

    /**
     * Get taxesLow
     *
     * @return integer 
     */
    public function getTaxesLow()
    {
        return $this->normalizedToFloat($this->taxesLow);
    }

    private function strToNormalized($str)
    {
        $str = str_replace(',', '.', $str);
        $str = str_replace(' ', '', $str);
        return intval(100 * floatval($str));
    }

    private function normalizedToFloat($int)
    {
        if($int === null) return null;
        return floatval($int / 100);
    }
}

src/JE/FinancesBundle/Form/SupplierInvoiceType.php
<?php

namespace JE\FinancesBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class SupplierInvoiceType extends AbstractType
{
        /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('ref', 'text', array(
                'label' => 'Référence',
            ))
            ->add('createdAt', 'datepicker', array(
                'label' => 'Date',
            ))
            ->add('supplier', 'text', array(
                'label' => 'Récepteur',
            ))
            ->add('description', 'text', array(
                'label' => 'Description',
            ))
            ->add('totalAmount', 'text', array(
                'label' => 'Montant TTC',
            ))
            ->add('taxesHigh', 'text', array(
                'label' => 'Montant TVA 19.6 %',
            ))
            ->add('taxesMedium', 'text', array(
                'label' => 'Montant TVA 7.0 %',
            ))
            ->add('taxesLow', 'text', array(
                'label' => 'Montant TVA 5.5 %',
            ))
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'JE\FinancesBundle\Entity\SupplierInvoice'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'je_financesbundle_supplierinvoice';
    }
}

src/JE/FinancesBundle/Controller/SupplierInvoiceController.php
<?php

namespace JE\FinancesBundle\Controller;

use JE\FinancesBundle\Entity\SupplierInvoice;
use JE\FinancesBundle\Form\SupplierInvoiceType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use JMS\SecurityExtraBundle\Annotation\Secure;
use Doctrine\ORM\EntityManager;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Form;
use Symfony\Component\HttpFoundation\Response;
use Knp\Component\Pager\Paginator;

class SupplierInvoiceController extends Controller
{
    /** @var  EntityManager */
    private $em;

    /** @var  Request */
    private $request;

    /**
     * @var Paginator
     */
    private $paginator;

    /**
     * @Secure(roles="ROLE_TREZ_VIEW")
     * @Template
     */
    public function indexAction($page, $sort, $direction)
    {
        $_GET['sort'] = $sort;
        $_GET['direction'] = $direction;
        $invoices = $this->em->getRepository('JEFinancesBundle:SupplierInvoice')->queryAll();
        $pagination = $this->paginator->paginate($invoices, $page, 40);

        return array(
            'invoices' => $pagination,
        );
    }

    /**
     * @Secure(roles="ROLE_TREZ_ADD")
     * @Template
     */
    public function newAction()
    {
        $invoice = new SupplierInvoice;

        return $this->handleForm($invoice);
    }

    /**
     * @Secure(roles="ROLE_TREZ_EDIT")
     * @Template
     */
    public function editAction(SupplierInvoice $invoice)
    {
        return $this->handleForm($invoice);
    }

    private function handleForm(SupplierInvoice $invoice)
    {
        $form = $this->createForm(new SupplierInvoiceType, $invoice);

        if($this->request->isMethod('POST')){
            $form->handleRequest($this->request);

            if($form->isValid()){
                $this->em->persist($invoice);
                $this->em->flush();

                return $this->redirect($this->generateUrl('je_finances_ff'));
            }
        }

        return array(
            'form' => $form->createView(),
        );
    }
}

src/JE/FinancesBundle/Resources/views/SupplierInvoice/edit.html.twig
{% extends '::layout.html.twig' %}

{% block content %}

    <h1 class="ui header">
        Editer le FF / RF
    </h1>
    <form class="ui blue form segment" method="post" novalidate>
        {{ form_widget(form) }}
        <button type="submit" class="ui blue labeled icon submit button">
            Editer <i class="pencil icon"></i>
        </button>
        <a href="{{ path('je_finances_ff') }}" class="ui labeled icon submit button">
            Annuler <i class="reply mail icon"></i>
        </a>
    </form>
{% endblock %}

src/JE/FinancesBundle/Resources/views/SupplierInvoice/index.html.twig
{% extends '::layout.html.twig' %}

{% block content %}
    <h1 class="ui header">
        Factures fournisseurs / RF
    </h1>

    <table class="ui compact table segment">
        <thead>
        <tr>
            {{ knp_pagination_sortable(invoices, "Référence", 'i.ref') }}
            {{ knp_pagination_sortable(invoices, "Date", 'i.createdAt') }}
            {{ knp_pagination_sortable(invoices, "Récepteur", 'i.supplier') }}
            <th>Déscription</th>
            <th>Montant HT</th>
            <th>Montant TTC</th>
            <th>19.6 %</th>
            <th>7.0 %</th>
            <th>5.5 %</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for invoice in invoices %}
        <tr>
            <td>{{ invoice.ref }}</td>
            <td>{{ invoice.createdAt|date('d/m/Y') }}</td>
            <td>{{ invoice.supplier }}</td>
            <td>{{ invoice.description }}</td>
            <td>{{ invoice.amount|money }}</td>
            <td>{{ invoice.totalAmount|money }}</td>
            <td>{{ invoice.taxesHigh|money }}</td>
            <td>{{ invoice.taxesMedium|money }}</td>
            <td>{{ invoice.taxesLow|money }}</td>
            <td>
                <div class="ui labeled icon top right pointing dropdown mini button">
                    <i class="settings icon"></i>
                    Actions
                    <div class="menu">
                        <a href="{{ path('je_finances_ff_edit', {ref:invoice.ref}) }}" class="item">
                            <i class="pencil icon"></i> Editer
                        </a>
                        <a class="item">
                            <i class="delete icon"></i> Supprimer
                        </a>
                    </div>
                </div>
            </td>
        </tr>
        {% else %}
            <tr>
                <td colspan="10">
                    Aucun FF / RF
                </td>
            </tr>
        {% endfor %}
        </tbody>
        <tfoot>
        <tr>
            <th colspan="10">
                <a class="ui green labeled icon button" href="{{ path('je_finances_ff_new') }}">
                    Nouveau <i class="plus icon"></i>
                </a>
                {{ knp_pagination_render(invoices) }}
            </th>
        </tr>
        </tfoot>
    </table>

{% endblock %}

src/JE/FinancesBundle/Resources/views/SupplierInvoice/new.html.twig
{% extends '::layout.html.twig' %}

{% block content %}

    <h1 class="ui header">
        Nouveau FF / RF
    </h1>
    <form class="ui green form segment" method="post" novalidate>
        {{ form_widget(form) }}
        <button type="submit" class="ui green labeled icon submit button">
            Créer <i class="plus icon"></i>
        </button>
        <a href="{{ path('je_finances_ff') }}" class="ui labeled icon submit button">
            Annuler <i class="reply mail icon"></i>
        </a>
    </form>
{% endblock %}