src/JE/FinancesBundle/Entity/CustomerInvoice.php
<?php

namespace JE\FinancesBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\ExecutionContextInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * CustomerInvoice
 *
 * @ORM\Table(name="je_customer_invoice")
 * @ORM\Entity(repositoryClass="JE\FinancesBundle\Entity\CustomerInvoiceRepository")
 * @Assert\Callback(methods={"checkDates"})
 * @UniqueEntity("fc")
 * @Gedmo\Uploadable(allowOverwrite = true, filenameGenerator = "SHA1")
 */
class CustomerInvoice
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="ref", type="string", length=40)
     * @Assert\NotBlank()
     * @Assert\Regex("/^\d+$/")
     */
    private $ref;

    /**
     * @var string
     *
     * @ORM\Column(name="fc", type="string", length=40, unique=true)
     * @Assert\NotBlank()
     * @Assert\Regex("/^FC\d+$/")
     */
    private $fc;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="issued_at", type="datetime")
     * @Assert\NotBlank()
     */
    private $issuedAt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="due_date", type="datetime")
     * @Assert\NotBlank()
     */
    private $dueDate;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="paid_at", type="datetime", nullable=true)
     */
    private $paidAt;

    /**
     * @var string
     *
     * @ORM\Column(name="client", type="string", length=255)
     * @Assert\NotBlank()
     */
    private $client;

    /**
     * @var integer
     *
     * @ORM\Column(name="percentage", type="integer")
     * @Assert\NotBlank()
     */
    private $percentage;

    /**
     * @var integer
     *
     * @ORM\Column(name="amount", type="integer")
     * @Assert\NotBlank()
     */
    private $amount;

    /**
     * @var integer
     *
     * @ORM\Column(name="taxes", type="integer")
     * @Assert\NotBlank()
     */
    private $taxes;

    /**
     * @var boolean
     *
     * @ORM\Column(name="paid", type="boolean")
     */
    private $paid;

    /**
     * @var string
     *
     * @ORM\Column(name="path", type="string", length=255, nullable=true)
     * @Gedmo\UploadableFilePath
     */
    private $path;

    /**
     * @Assert\File(
     *     maxSize="8M",
     *     mimeTypes = {
     *      "application/pdf",
     *      "application/zip", "application/x-compressed", "application/x-zip-compressed", "multipart/x-zip",
     *      "application/excel", "application/vnd.ms-excel", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "application/x-excel", "application/x-msexcel",
     *      "application/msword", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"},
     *     mimeTypesMessage = "Fichier ZIP, PDF, Word ou Excel",
     *     maxSizeMessage = "Fichier trop gros (8Mo max)"
     * )
     */
    private $file;

    public function __construct(Variable $defaultTaxes = null)
    {
        $this->paid = false;
        $this->fc = 'FC';
        $this->issuedAt = new \DateTime;
        $this->dueDate = (new \DateTime)->add(new \DateInterval('P1M'));

        if($defaultTaxes !== null)
            $this->setTaxes($defaultTaxes->getValue());
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set ref
     *
     * @param string $ref
     * @return CustomerInvoice
     */
    public function setRef($ref)
    {
        $this->ref = $ref;
    
        return $this;
    }

    /**
     * Get ref
     *
     * @return string 
     */
    public function getRef()
    {
        return $this->ref;
    }

    /**
     * Set fc
     *
     * @param string $fc
     * @return CustomerInvoice
     */
    public function setFc($fc)
    {
        $this->fc = $fc;
    
        return $this;
    }

    /**
     * Get fc
     *
     * @return string 
     */
    public function getFc()
    {
        return $this->fc;
    }

    /**
     * Set issuedAt
     *
     * @param \DateTime $issuedAt
     * @return CustomerInvoice
     */
    public function setIssuedAt($issuedAt)
    {
        $this->issuedAt = $issuedAt;
    
        return $this;
    }

    /**
     * Get issuedAt
     *
     * @return \DateTime 
     */
    public function getIssuedAt()
    {
        return $this->issuedAt;
    }

    /**
     * Set dueDate
     *
     * @param \DateTime $dueDate
     * @return CustomerInvoice
     */
    public function setDueDate($dueDate)
    {
        $this->dueDate = $dueDate;
    
        return $this;
    }

    /**
     * Get dueDate
     *
     * @return \DateTime 
     */
    public function getDueDate()
    {
        return $this->dueDate;
    }

    /**
     * @param \DateTime $paidAt
     */
    public function setPaidAt($paidAt)
    {
        $this->paidAt = $paidAt;
    }

    /**
     * @return \DateTime
     */
    public function getPaidAt()
    {
        return $this->paidAt;
    }

    /**
     * Set client
     *
     * @param string $client
     * @return CustomerInvoice
     */
    public function setClient($client)
    {
        $this->client = $client;
    
        return $this;
    }

    /**
     * Get client
     *
     * @return string 
     */
    public function getClient()
    {
        return $this->client;
    }

    /**
     * Set percentage
     *
     * @param integer $percentage
     * @return CustomerInvoice
     */
    public function setPercentage($percentage)
    {
        $this->percentage = $this->strToNormalized($percentage);
    
        return $this;
    }

    /**
     * Get percentage
     *
     * @return integer 
     */
    public function getPercentage()
    {
        return $this->normalizedToFloat($this->percentage);
    }

    /**
     * Set amount
     *
     * @param integer $amount
     * @return CustomerInvoice
     */
    public function setAmount($amount)
    {
        $this->amount = $this->strToNormalized($amount);
    
        return $this;
    }

    /**
     * Get amount
     *
     * @return integer 
     */
    public function getAmount()
    {
        return $this->normalizedToFloat($this->amount);
    }

    /**
     * Set taxes
     *
     * @param integer $taxes
     * @return CustomerInvoice
     */
    public function setTaxes($taxes)
    {
        $this->taxes = $this->strToNormalized($taxes);
    
        return $this;
    }

    /**
     * Get taxes
     *
     * @return integer 
     */
    public function getTaxes()
    {
        return $this->normalizedToFloat($this->taxes);
    }

    /**
     * Get taxes amount
     *
     * @return integer
     */
    public function getTaxesAmount()
    {
        return $this->getAmount() * $this->getTaxes() / 100;
    }

    /**
     * Get taxes amount
     *
     * @return integer
     */
    public function getTotalAmount()
    {
        return $this->getAmount() + $this->getTaxesAmount();
    }

    /**
     * Set paid
     *
     * @param boolean $paid
     * @return CustomerInvoice
     */
    public function setPaid($paid)
    {
        $this->paid = $paid;
    
        return $this;
    }

    /**
     * Get paid
     *
     * @return boolean 
     */
    public function getPaid()
    {
        return $this->paid;
    }

    /**
     * Set path
     *
     * @param string $path
     * @return CustomerInvoice
     */
    public function setPath($path)
    {
        $this->path = $path;

        return $this;
    }

    /**
     * Get path
     *
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Get web path
     *
     * @return string
     */
    public function getWebPath()
    {
        return preg_replace('#^.+\.\./www/(.+)$#', '$1', $this->getPath());
    }

    /**
     * @param mixed $file
     */
    public function setFile($file)
    {
        $this->file = $file;
    }

    /**
     * @return mixed
     */
    public function getFile()
    {
        return $this->file;
    }

    public function hasFile()
    {
        return $this->path !== null;
    }

    private function strToNormalized($str)
    {
        $str = str_replace(',', '.', $str);
        $str = str_replace(' ', '', $str);
        return intval(100 * floatval($str));
    }

    private function normalizedToFloat($int)
    {
        if($int === null) return null;
        return floatval($int / 100);
    }

    public function checkDates(ExecutionContextInterface $context)
    {
        if($this->dueDate !== null){
            if($this->issuedAt->diff($this->dueDate)->invert === 1)
                $context->addViolationAt('dueDate', "La date d'échéance ne peut pas être avant la date d'émmission");
        }
    }
}

src/JE/FinancesBundle/Form/CustomerInvoiceType.php
<?php

namespace JE\FinancesBundle\Form;

use JE\FinancesBundle\Form\EventListener\AddPaidAtSubscriber;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class CustomerInvoiceType extends AbstractType
{
        /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('ref', 'text', array(
                'label' => 'Référence',
            ))
            ->add('fc', 'text', array(
                'label' => 'FC',
            ))
            ->add('issuedAt', 'datepicker', array(
                'label' => "Date d'émmission",
            ))
            ->add('dueDate', 'datepicker', array(
                'label' => "Date d'échéance",
            ))
            ->add('client', 'text', array(
                'label' => 'Client',
            ))
            ->add('percentage', 'text', array(
                'label' => 'Pourcentage',
            ))
            ->add('amount', 'text', array(
                'label' => 'Montant HT',
            ))
            ->add('taxes', 'text', array(
                'label' => 'TVA',
            ))
            ->add('file', 'file', array(
                'label' => 'Fichier',
            ))
        ;

        $builder->addEventSubscriber(new AddPaidAtSubscriber);
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'JE\FinancesBundle\Entity\CustomerInvoice'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'je_financesbundle_customerinvoice';
    }
}

src/JE/FinancesBundle/Controller/CustomerInvoiceController.php
<?php

namespace JE\FinancesBundle\Controller;

use JE\FinancesBundle\Entity\CustomerInvoice;
use JE\FinancesBundle\Form\CustomerInvoiceType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use JMS\SecurityExtraBundle\Annotation\Secure;
use Doctrine\ORM\EntityManager;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Form;
use Symfony\Component\HttpFoundation\Response;
use Knp\Component\Pager\Paginator;
use Stof\DoctrineExtensionsBundle\Uploadable\UploadableManager;

class CustomerInvoiceController extends Controller
{
    /** @var  EntityManager */
    private $em;

    /** @var  Request */
    private $request;

    /**
     * @var Paginator
     */
    private $paginator;

    /**
     * @var UploadableManager
     */
    private $uploadableManager;

    /**
     * @Secure(roles="ROLE_TREZ_VIEW")
     * @Template
     */
    public function indexAction($page, $sort, $direction)
    {
        $_GET['sort'] = $sort;
        $_GET['direction'] = $direction;
        $invoices = $this->em->getRepository('JEFinancesBundle:CustomerInvoice')->queryAll();
        $pagination = $this->paginator->paginate($invoices, $page, 40);

        return array(
            'invoices' => $pagination,
        );
    }

    /**
     * @Secure(roles="ROLE_TREZ_ADD")
     * @Template
     */
    public function newAction()
    {
        $invoice = new CustomerInvoice($this->em->getRepository('JEFinancesBundle:Variable')->findOneBySlug('tva_high'));

        return $this->handleForm($invoice);
    }

    /**
     * @Secure(roles="ROLE_TREZ_EDIT")
     * @Template
     */
    public function editAction(CustomerInvoice $invoice)
    {
        return $this->handleForm($invoice);
    }

    /**
     * @Secure(roles="ROLE_TREZ_EDIT")
     */
    public function paidAction(CustomerInvoice $invoice)
    {
        $invoice->setPaid(true);
        $invoice->setPaidAt(new \DateTime);

        $this->em->persist($invoice);
        $this->em->flush();

        return new Response('success');
    }

    /**
     * @Secure(roles="ROLE_TREZ_EDIT")
     */
    public function unpaidAction(CustomerInvoice $invoice)
    {
        $invoice->setPaid(false);

        $this->em->persist($invoice);
        $this->em->flush();

        return $this->redirect($this->generateUrl('je_finances_fc'));
    }

    private function handleForm(CustomerInvoice $invoice)
    {
        $form = $this->createForm(new CustomerInvoiceType, $invoice);

        if($this->request->isMethod('POST')){
            $form->handleRequest($this->request);

            if($form->isValid()){
                $this->em->persist($invoice);
                if($invoice->getFile()) $this->uploadableManager->markEntityToUpload($invoice, $invoice->getFile());
                $this->em->flush();

                return $this->redirect($this->generateUrl('je_finances_fc'));
            }
        }

        return array(
            'form' => $form->createView(),
        );
    }
}

src/JE/FinancesBundle/Resources/views/CustomerInvoice/edit.html.twig
{% extends '::layout.html.twig' %}

{% block content %}

    <h1 class="ui header">
        Editer le FC
    </h1>
    <form class="ui blue form segment" method="post" {{ form_enctype(form) }} novalidate>
        {{ form_widget(form) }}
        <button type="submit" class="ui blue labeled icon submit button">
            Editer <i class="pencil icon"></i>
        </button>
        <a href="{{ path('je_finances_fc') }}" class="ui labeled icon submit button">
            Annuler <i class="reply mail icon"></i>
        </a>
    </form>
{% endblock %}

src/JE/FinancesBundle/Resources/views/CustomerInvoice/index.html.twig
{% extends '::layout.html.twig' %}

{% block content %}
    <h1 class="ui header">
        Factures clients
    </h1>

    <table class="ui compact table segment">
        <thead>
        <tr>
            {{ knp_pagination_sortable(invoices, "Référence", 'i.ref') }}
            {{ knp_pagination_sortable(invoices, "FC", 'i.fc') }}
            {{ knp_pagination_sortable(invoices, "Date d'émmission", 'i.issuedAt') }}
            {{ knp_pagination_sortable(invoices, "Date d'échéance", 'i.dueDate') }}
            {{ knp_pagination_sortable(invoices, "Client", 'i.client') }}
            <th>Pourcentage</th>
            <th>Montant HT</th>
            <th>Montant TVA</th>
            <th>Montant TTC</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for invoice in invoices %}
        <tr{% if invoice.paid %} class="positive" {% endif %}>
            <td>{{ invoice.ref }}</td>
            <td>{{ invoice.fc }}</td>
            <td>{{ invoice.issuedAt|date('d/m/Y') }}</td>
            <td{% if invoice.dueDate < date('now') and not invoice.paid %} class="error"{% endif %}>
                {{ invoice.dueDate|date('d/m/Y') }}
            </td>
            <td>{{ invoice.client }}</td>
            <td>{{ invoice.percentage }} %</td>
            <td>{{ invoice.amount|money }}</td>
            <td>{{ invoice.taxesAmount|money }}</td>
            <td>{{ invoice.totalAmount|money }}</td>
            <td>
                <div class="ui labeled icon top right pointing dropdown mini button">
                    <i class="settings icon"></i>
                    Actions
                    <div class="menu">
                        {% if invoice.paid %}
                            <a href="{{ path('je_finances_fc_unpaid', {fc:invoice.fc}) }}" class="item">
                                <i class="reply mail icon"></i> Annuler paiment
                            </a>
                        {% else %}
                            <div data-row-action="{{ url('je_finances_fc_paid', {fc:invoice.fc}) }}" class="item">
                                <i class="check icon"></i> Payé
                            </div>
                        {% endif %}
                        {% if invoice.hasFile %}
                            <a href="{{ asset(invoice.webPath) }}" class="item">
                                <i class="file icon"></i> Document
                            </a>
                        {% endif %}
                        <a href="{{ path('je_finances_fc_edit', {fc:invoice.fc}) }}" class="item">
                            <i class="pencil icon"></i> Editer
                        </a>
                        <a class="item">
                            <i class="delete icon"></i> Supprimer
                        </a>
                    </div>
                </div>
            </td>
        </tr>
        {% else %}
            <tr>
                <td colspan="10">
                    Aucun FC
                </td>
            </tr>
        {% endfor %}
        </tbody>
        <tfoot>
        <tr>
            <th colspan="10">
                <a class="ui green labeled icon button" href="{{ path('je_finances_fc_new') }}">
                    Nouveau <i class="plus icon"></i>
                </a>
                {{ knp_pagination_render(invoices) }}
            </th>
        </tr>
        </tfoot>
    </table>

{% endblock %}

src/JE/FinancesBundle/Resources/views/CustomerInvoice/new.html.twig
{% extends '::layout.html.twig' %}

{% block content %}

    <h1 class="ui header">
        Nouveau FC
    </h1>
    <form class="ui green form segment" method="post" {{ form_enctype(form) }} novalidate>
        {{ form_widget(form) }}
        <button type="submit" class="ui green labeled icon submit button">
            Créer <i class="plus icon"></i>
        </button>
        <a href="{{ path('je_finances_fc') }}" class="ui labeled icon submit button">
            Annuler <i class="reply mail icon"></i>
        </a>
    </form>
{% endblock %}